FROM public.ecr.aws/docker/library/python:3.10.15-alpine3.20

ARG DOMAIN
ARG OAUTH_UID
ARG OAUTH_SECRET
ARG OAUTH_CALLBACK
ARG DBNAME
ARG DBUSER
ARG DBPASSWORD

ENV DOMAIN=$DOMAIN
ENV OAUTH_UID=$OAUTH_UID
ENV OAUTH_SECRET=$OAUTH_SECRET
ENV OAUTH_CALLBACK=$OAUTH_CALLBACK
ENV DBNAME=$DBNAME
ENV DBUSER=$DBUSER
ENV DBPASSWORD=$DBPASSWORD

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy application code
COPY . .

# Expose port 8000 for the development server
EXPOSE 8000

# Run the command to start the Django development server
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application"]