# Generated by Django 5.1.1 on 2024-10-15 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_participant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament'),
        ),
    ]
