# Generated by Django 5.1.1 on 2024-10-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournamentmatch_round_alter_participant_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='player1_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='player2_goals',
            field=models.IntegerField(default=0),
        ),
    ]
