# Generated by Django 5.1.1 on 2024-10-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournamentmatch_player1_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
