# Generated by Django 5.1.1 on 2024-09-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='boostFactor',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='boostsEnabled',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='customCoronaType',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='customStarColor',
            field=models.CharField(default='#DC1010', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='customStarIntensity',
            field=models.DecimalField(decimal_places=0, default=4, max_digits=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='customStarSize',
            field=models.DecimalField(decimal_places=0, default=4, max_digits=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gameDuration',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gargantuaColor',
            field=models.CharField(default='#c5e0e2', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gargantuaIntensity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gargantuaSize',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='powerEnabled',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='startFlag',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
